### PR TITLE
🌐 Update cs.dict.itop-approval-portal.php

### PR DESCRIPTION
**Pull request by Stetinac**
Translate module to CZ

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello Pavel,

Thanks for all the translations! Could you send me an email to guillaume.lajarige combodo.com with your fullname / postal address so we can send you [thankful stickers](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#-we-are-thankful)?

Cheers,
Guillaume

**Comment by Stetinac** [comment]
> Hello Pavel,
> 
> Thanks for all the translations! Could you send me an email to guillaume.lajarige combodo.com with your fullname / postal address so we can send you [thankful stickers](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#-we-are-thankful)?
> 
> Cheers, Guillaume

Hello,

send.

Thank you,

Stetinac

**Comment by Stetinac** [comment]
> Hello Pavel,
> 
> Thanks for all the translations! Could you send me an email to guillaume.lajarige combodo.com with your fullname / postal address so we can send you [thankful stickers](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#-we-are-thankful)?
> 
> Cheers, Guillaume

Delivered tomorow...

Thank You

**Comment by Molkobain** [comment]
Thank you for your contributions :)

**Pull request merged**
